#ifndef OPENPOSE__EXPERIMENTAL__PRODUCER__HEADERS_HPP
#define OPENPOSE__EXPERIMENTAL__PRODUCER__HEADERS_HPP

// producer module
// #include "wPoseLoader.hpp"

#endif // OPENPOSE__EXPERIMENTAL__PRODUCER__HEADERS_HPP
