#ifndef OPENPOSE_EXPERIMENTAL_PRODUCER_HEADERS_HPP
#define OPENPOSE_EXPERIMENTAL_PRODUCER_HEADERS_HPP

// producer module
// #include "wPoseLoader.hpp"

#endif // OPENPOSE_EXPERIMENTAL_PRODUCER_HEADERS_HPP
