#ifndef OPENPOSE_EXPERIMENTAL_FILESTREAM_HEADERS_HPP
#define OPENPOSE_EXPERIMENTAL_FILESTREAM_HEADERS_HPP

// storage module
#include "wCocoJsonSaver.hpp"

#endif // OPENPOSE_EXPERIMENTAL_FILESTREAM_HEADERS_HPP
